name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
      branches: ["main"]

#jobs - определение задач для выполнения
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health_timeout 5s
          --health_retries 5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # копируем в облако GitHub

      - name: Set up Python
        uses: actions/setup-python@v3 # устанавливаем python
        with:
          python-version: '3.13'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Requirements
        run:
          pip install -r requirements.txt

      - name: Run migrations
        run:
          python manage.py migrate
        env:
          DB_NAME: test_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DEBUG: 'False'

      - name: Run Tests
        run:
          python manage.py test # запуск тестов
        env:
          DB_NAME: test_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DEBUG: 'False'